# Generated by Django 2.2.13 on 2020-08-13 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Year_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchYear', models.CharField(blank=True, max_length=500)),
                ('Project_Name', models.CharField(blank=True, max_length=500)),
                ('Project_Supervisor', models.CharField(blank=True, max_length=500)),
                ('External_Supervisor', models.CharField(blank=True, max_length=500)),
                ('Co_Supervisor', models.CharField(blank=True, max_length=500)),
                ('Project_Id', models.CharField(max_length=500)),
                ('Students', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
